name: reinvent_shared.v2.1
channels:
  - rdkit
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cycler=0.10.0
  - dataclasses=0.7
  - dill=0.3.1.1
  - ipython=7.16.1
  - ipywidgets=7.5.1
  - jinja2=2.11.2
  - joblib=0.14.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.2.0
  - matplotlib=3.2.2
  - multiprocess=0.70.9
  - numpy=1.17.3
  - pandas=1.1.0
  - pandoc=2.10
  - pandocfilters=1.4.2
  - pathos=0.2.5
  - pillow=7.0.0
  - pip=20.0.2
  - py-boost=1.67.0
  - pytest=5.3.0
  - python=3.6.5
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - rdkit=2019.09.1.0
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - tensorboard=1.14.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tqdm=4.38.0
  - xz=5.2.4
  - zeromq=4.3.1
  - zstd=1.3.7
  - openpyxl=3.0.6
  - seaborn=0.11.1
  - numba=0.52.0
  - pip:
    - pandarallel==1.4.8
    - pyarrow==1.0.1   

